apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  tls:
  - hosts:
    - www.rewritecode.ru
    - rewritecode.ru
    secretName: app-tls
  rules:
    - host: www.rewritecode.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codehelper-clusterip-srv
                port:
                  number: 80
          - path: /i
            pathType: Prefix
            backend:
              service:
                name: images-clusterip-srv
                port:
                  number: 8080
    - host: rewritecode.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codehelper-clusterip-srv
                port:
                  number: 80
          - path: /i
            pathType: Prefix
            backend:
              service:
                name: images-clusterip-srv
                port:
                  number: 8080