apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
  namespace: default
spec:
  storageClassName: ""
  volumeName: mssql-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  claimRef:
    name: mssql-claim
    namespace: default
  hostPath:
    path: "/var/lib/k8s-pvs"