apiVersion: v1
kind: Service
metadata:
  name: nodeport-srv
spec:
  type: NodePort
  selector:
    app: images-app
  ports:
    - name: images-app
      protocol: TCP
      port: 8081
      targetPort: 8081